### ISSUE TITLE
Can't instantiate after going back to the previous step

### ISSUE THREAD

**Issue by statictype** [paritytech/substrate-contracts-explorer#176]
after un-queuing a transaction when going back to step 2, it's not possible to queue it again
 
to reproduce:
go through the instantiation form all the way to step 3 and back to step 2 and to step 3 again

**Comment by achimcc** [comment]
I did some debugging:

In Step 3, when going back, we "unfinalize" the finalized transaction. As part of this, we unqueue the transaction, but we forget to invalidate the txId after removing the transaction from the queue. I'll create a small PR which fixes this.
